### ISSUE TITLE
cmake Error when building per README

### ISSUE THREAD

**Issue by mintakka** [pimoroni/picosystem#4]
Trying to build per the README on macOS. I have the pico SDK and build tools set up correctly (I think) but am getting a cmake error

```
CMake Error at examples/snake/CMakeLists.txt:10 (find_package):
By not providing "FindPICOSYSTEM.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"PICOSYSTEM", but CMake did not find one.

Could not find a package configuration file provided by "PICOSYSTEM" with
any of the following names:

PICOSYSTEMConfig.cmake
picosystem-config.cmake

Add the installation prefix of "PICOSYSTEM" to CMAKE_PREFIX_PATH or set
"PICOSYSTEM_DIR" to a directory containing one of the above files.  If
"PICOSYSTEM" provides a separate development package or SDK, be sure it has
 been installed.
```

I can fix this manually by running cmake build flag `-DPICOSYSTEM_DIR:PATH=/Users/NAME/picosystem` (path set to root of where I cloned the repo) . This solves the issue and I can build the examples and run on the system. I am not sure whether or how to make changes to the CMakeLists.txt file to solve this at the root. 

Happy to close if this is user error on my end :) .

**Comment by ahnlak** [comment]
Have you got an updated copy of the repo - I *think* this was fixed by https://github.com/pimoroni/picosystem/pull/3 ?

(or at least, I got exactly the same on Linux until that PR)

**Comment by mintakka** [comment]
Interesting. Yes I am having this issue on a clean repo as of when I posted this. I'll install a Linux VM and see if that yields anything different.

**Comment by ahnlak** [comment]
Hmm, you're right, latest repo is doing that to me too again. As you say, defining PICOSYSTEM_DIR gets around it (and I use it for building out-of-tree stuff), but it really should work for the examples!

**Comment by mintakka** [comment]
so I added `set(PICOSYSTEM_DIR "/Users/matt/Projects/picosystem")` into the root level CMakeLists.txt file at line 9 and that works for me as a more streamlined solution. Unfortunately, I'm not familiar enough with CMake syntax to define the path to PICOSYSTEM_DIR programmatically as opposed to hard coding it in for my specific case - otherwise I'd start a Pull.

**Comment by aiecee** [comment]
I've created a quick and dirty boilerplate [here](https://github.com/aiecee/picosystem-boilerplate) people can use in the meantime until someone better versed in the art of CMake comes along and makes a better one.

**Comment by mintakka** [comment]
So just putting 

`set(PICOSYSTEM_DIR "..")`

seems would work for all users as long as your build folder lives alongside the top-level CMakeLists.txt

**Comment by Gadgetoid** [comment]
Note: I've got an incoming PR which will overhaul some of the CMake stuff, including setting sensible guess paths for `PICOSYSTEM_DIR` since having to specify it for examples is utterly silly.
