### ISSUE TITLE
picosystem SDK uses default pico SDK memory map

### ISSUE THREAD

**Issue by og-syn** [pimoroni/picosystem#54]
(At least) when installed according to instructions, the picosystem SDK builds using the default pico SDK memory map (pico-sdk/src/rp2_common/pico_standard_link/memmap_default.ld).

This specifies 2k of flash:

```
 MEMORY
 {
    FLASH(rx) : ORIGIN = 0x10000000, LENGTH = 2048k

```

This limits the .rodata section of ELF files to 2M of memory. This limitation seems to come from the standard Pi Pico. However, Picosystems have a 16 MB flash memory which can hold much more. Bumping up the length to e.g. 8192k (or more, up to 16384k I guess) allows building much larger projects.

This is especially important when #include'ing bitmaps, sprites or similar. It would be super nice if the picosystem SDK shipped with a custom memory map which fixes this problem.

Tested: up to 8192k seems to be working just fine. ELF files with e.g. ~3.8 MB of .rodata usage just work after the flash length is edited to accommodate.

Workarounds: I suppose it's possible, though much less convenient, to manually attach binary data at the end of a UF2 file (or directly on the device) with picotool or equivalent.

**Comment by Gadgetoid** [comment]
I thought building with "-DPICO_BOARD=pimoroni_picosystem" would handle this.

Looks like we have to ship our own linker script and use `pico_set_linker_script`:

https://github.com/raspberrypi/pico-sdk/blob/bfcbefafc5d2a210551a4d9d80b4303d4ae0adf7/src/rp2_common/pico_standard_link/CMakeLists.txt#L35-L39
