### ISSUE TITLE
MicroPython - Can't draw to offscreen buffer and blit buffer to screen

### ISSUE THREAD

**Issue by aiecee** [pimoroni/picosystem#68]
Open the REPL and run:
````
>>> b=Buffer(120,120)
>>> target(b)
>>> sprite(0,20,20)
>>> target()
>>> blit(b,0,0,120,120,0,0)
>>> flip()
````

Would be useful for tile maps or backgrounds where you don't want to redraw multiple sprites/text/shapes every tick. Instead draw to a buffer once and then blit the buffer to the screen every tick

**Comment by Gadgetoid** [comment]
You need a “blend(COPY)” in there before drawing the sprite, since by default a new buffer is initialised to transparent and regular blends end up… transparent 😩

**Comment by aiecee** [comment]
Magic that worked! Just for the record:
````
>>> b=Buffer(120,120)
>>> target(b)
>>> blend(COPY)
>>> sprite(0,20,20)
>>> blend()
>>> target()
>>> blit(b,0,0,120,120,0,0)
>>> flip()
````
