### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by PaulskPt** [pimoroni/picosystem#86]
Following the instructions, everything, while building went almost OK, except this error:

![Captura de Ecrã (1038)](https://user-images.githubusercontent.com/9107950/186983262-2b1c3709-7653-4f31-a074-3c4c8c8e8ce6.png)

**Comment by Gadgetoid** [comment]
Sorry those instructions were outdated recently, you should use the branch `experimental/picosystem-1.19` since `MP_REGISTER_MODULE` changes between v1.18 and v1.19.

**Comment by PaulskPt** [comment]
Thank you for your response, Philip. I used the branch v1.19. It built 100% OK. Issue closed.
